#pragma kernel CSMain

RWTexture3D<float> Result;

RWStructuredBuffer<float3> Points;
int PointCount;
float ValueDivisor;

[numthreads(8, 8, 8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 pos = float3(id.x, id.y, id.z);

	float dist = 9999999999999999999.0;

	for (int i = 0; i < PointCount; i++) {
		float d = length(pos - Points[i]);
		if (d < dist) {
			dist = d;
		}
	}


	Result[id.xyz] = (dist / ValueDivisor);
}
